version: '3.8'

services:
  shopify_db_dev:
    container_name: shopify_db_dev
    image: postgres:15
    volumes:
      - shopify_data_dev:/var/lib/postgresql/data
    env_file:
      - .env.local
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    command: -p 5432

  shopify_redis_dev:
    image: redis:7
    container_name: shopify_redis_dev
    ports:
      - '6379:6379'

  shopify_api_dev:
    container_name: shopify_api_dev
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
      - shopify_db_dev
      - shopify_redis_dev
      - shopify_minio_dev
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    env_file:
      - .env.local
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npx prisma migrate deploy && npm run start:dev"

  shopify_minio_dev:
    container_name: shopify_minio_dev
    image: minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - shopify_minio_dev_data:/data
    environment:
      - MINIO_ROOT_USER=${S3_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${S3_SECRET_KEY}
    command: server /data --console-address ":9001"

volumes:
  shopify_data_dev: {}
  shopify_minio_dev_data: {}
